In [1]:
import pandas as pd
import sqlite3

In [5]:
from functions.sql_functions import sql_connect
import logging

logger = logging.getLogger(__name__)
sql_con = sql_connect('orders', logger)

In [6]:
import datetime as dt

df = sql_con.get_all_orders()
# df = df[df['stage']=='accepted_deliverman']
# df['last_change'] = pd.to_datetime(df['last_change'])
# df['current_time'] = dt.datetime.now()
# df['time_delta'] = df['current_time'] - df['last_change']
# df['time_delta'] = df['time_delta'].apply(lambda x: x.seconds)
# df = df[df['time_delta'] > 10]
# records = df.to_dict('records')
# records
df.tail()

,track_num,country,address,pass,descriprion,price,path_image,stage,last_change,manager_id,manager_name,warehouser_id,warehouser_name,warehouse_messageid,delivery_group_messageid,deliveryman_id,deliveryman_name,delivery_private_messageid
6,111222,2,3,4,5,6,images/111222_image_2023-06-13 23:49:44.140230...,created,2023-06-13 23:49:57.288528,396022903,Vanka Zhukov,None,None,None,None,None,None,None
7,1112223,2,3,4,5,6,images/1112223_image_2023-06-13 23:51:59.42604...,accepted_deliverman,2023-06-14 00:11:20.411075,396022903,Vanka Zhukov,396022903,Vanka Zhukov,None,8144,396022903,Vanka Zhukov,None
8,1112224,2,3,4,5,6,images/1112224_image_2023-06-14 00:13:42.57475...,created,2023-06-14 00:14:13.586512,396022903,Vanka Zhukov,None,None,None,None,None,None,None
9,1112225,2,3,4,5,6,images/1112225_image_2023-06-14 00:18:22.14505...,delivered,2023-06-14 00:19:16.123312,396022903,Vanka Zhukov,396022903,Vanka Zhukov,8223,8231,396022903,Vanka Zhukov,8233
10,1112226,2,3,4,5,6,images/1112226_image_2023-06-14 00:25:29.92063...,delivered,2023-06-14 00:26:16.832179,396022903,Vanka Zhukov,396022903,Vanka Zhukov,8267,8279,396022903,Vanka Zhukov,8282

In [3]:
sql_con.get_order('CQ877760132DE')

{'track_num': 'CQ877760132DE',
 'country': 'üá´üáÆ',
 'address': 'Posti, K-Market Kannelm√§ki Klaneettitie 7, 00420 HELSINKI',
 'pass': '042926',
 'descriprion': '–ö—Ä–æ—Å—Å–æ–≤–∫–∏ Nike Lebron James 9',
 'price': '152–µ–≤—Ä–æ',
 'path_image': 'images/CQ877760132DE_image.jpg',
 'stage': 'created',
 'last_change': '2023-06-12 10:38:19.963587',
 'manager_id': '594809568',
 'manager_name': 'KosteominD KosteominD',
 'warehouser_id': None,
 'warehouser_name': None,
 'warehouse_messageid': None,
 'delivery_group_messageid': None,
 'deliveryman_id': None,
 'deliveryman_name': None,
 'delivery_private_messageid': None}