In [1]:
import pandas as pd
import sqlite3

In [15]:
from functions.sql_functions import sql_connect
import logging

logger = logging.getLogger(__name__)
sql_con = sql_connect('orders', logger)

In [19]:
import datetime as dt

df = sql_con.get_all_orders()
# df = df[df['stage']=='accepted_deliverman']
# df['last_change'] = pd.to_datetime(df['last_change'])
# df['current_time'] = dt.datetime.now()
# df['time_delta'] = df['current_time'] - df['last_change']
# df['time_delta'] = df['time_delta'].apply(lambda x: x.seconds)
# df = df[df['time_delta'] > 10]
# records = df.to_dict('records')
# records
df.tail()

,track_num,country,address,pass,descriprion,price,path_image,stage,last_change,manager_id,...,warehouser_name,warehouse_messageid,delivery_group_messageid,deliveryman_id,deliveryman_name,delivery_private_messageid,admin_group_messageid,warehouse_mediaid,delivery_group_mediaid,delivery_private_mediaid
71,test54,q,w,e,r,t,/home/ivan/Projects/git/Project/delivery/image...,in_warehouse,2023-08-20 03:12:06.998976,396022903,...,Vanka Zhukov,1573,1679,None,None,None,1575,1572,1678,None
72,test55,q,w,e,r,t,/home/ivan/Projects/git/Project/delivery/image...,in_warehouse,2023-08-20 03:11:58.200594,396022903,...,Vanka Zhukov,1597,None,None,None,None,1599,1596,None,None
73,test56,q,w,e,r,t,/home/ivan/Projects/git/Project/delivery/image...,in_warehouse,2023-08-20 03:13:48.156804,396022903,...,Vanka Zhukov,1620,1681,None,None,None,1622,1619,1680,None
74,test57,q,w,e,r,t,/home/ivan/Projects/git/Project/delivery/image...,accepted_deliverman,2023-08-20 03:16:58.465400,396022903,...,Vanka Zhukov,1643,1683,396022903,Vanka Zhukov,1689,1645,1642,1682,1688
75,test58,q,w,e,r,t,/home/ivan/Projects/git/Project/delivery/image...,accepted_deliverman,2023-08-20 03:16:11.799173,396022903,...,Vanka Zhukov,1666,1685,396022903,Vanka Zhukov,1687,1668,1665,1684,1686

In [14]:
con = sqlite3.connect(f'database/orders.db')
cur = con.cursor()
query = f"ALTER TABLE orders ADD COLUMN delivery_private_mediaid TEXT;"
cur.execute(query)

In [2]:
conn=sqlite3.connect('database/orders.db')
curs=conn.cursor()
curs.execute("DELETE  FROM orders WHERE track_num = 'teset88';")
conn.commit()
conn.close()

In [8]:
from inspect import getsourcefile
from os.path import abspath


abspath(getsourcefile(lambda:0))

'/tmp/ipykernel_586637/1586597091.py'